<?xml version="1.0"?>
<robot name="agv" xmlns:xacro="http://ros.org/wiki/xacro">
<!-- DEFINE -->
  
  <material name="Black">
    <color rgba="0.0 0.0 0.0 1.0"/>
  </material>

  <material name="White">
    <color rgba="1.0 1.0 1.0 1.0"/>
  </material>
  
  <!-- AGV Base -->
  <xacro:property name="agv_base_height" value="0.27" />
  <xacro:property name="agv_base_width" value="0.5" />
  <xacro:property name="agv_base_length" value="0.7" />
  <xacro:property name="agv_base_mass" value="1.0" />

  <!--All units in m-kg-s-radians unit system -->
  <xacro:property name="M_PI" value="3.1415926535897931" />
  <xacro:property name="M_PI_2" value="1.570796327" />
  <xacro:property name="DEG_TO_RAD" value="0.017453293" />
  
  <!-- Macro for calculating inertia of cube -->
  <xacro:macro name="cuboid_inertia" params="m w d h">
    <inertia  ixx="${m*(w*w+h*h)/12}" ixy = "0" ixz = "0"
              iyy="${m*(d*d+h*h)/12}" iyz = "0"
              izz="${m*(d*d+w*w)/12}" /> 
  </xacro:macro>
  
<!-- DEFINE END -->


  <!-- BASE-FOOTPRINT -->
  <!--<link name="base_footprint"/>
  <gazebo reference="base_footprint">
    <material>Gazebo/White</material>
    <gravity>true</gravity>
    <dampingFactor>0.0</dampingFactor>
    <maxVel>100000.0</maxVel>
    <minDepth>0.01</minDepth>
    <mu1>0.0</mu1>
    <mu2>0.0</mu2>
    <fdir1>1 0 0</fdir1>
    <kp>0.0</kp>
    <kd>0.0</kd>
    <selfCollide>false</selfCollide>
    <maxContacts></maxContacts>
    <laserRetro></laserRetro>
  </gazebo>-->
  
  <!-- AGV_BASE_LINK -->
  <!--<joint name="base_footprint_agv_base_joint" type="fixed">
    <origin xyz="0 0 ${agv_base_height/2+0.13}" rpy="0 0 0" />
    <parent link="base_footprint"/>
    <child link="agv_base_link" />
    <axis xyz="0 0 1" rpy="0 0"/>
    <calibraion rising="0.0" falling="0.0">
    <dynamics damping="10000.0" friction="100000.0"/>
    <limit effort="1000000.0" velocity="100.0"/>
  </joint>
  <gazebo reference="base_footprint_agv_base_joint">
    <stopCfm></stopCfm>
    <stopErp></stopErp>
    <provideFeedback>true</provideFeedback>
    <implicitSpringDamper>true</implicitSpringDamper>
    <fudgeFactor></fudgeFactor>
  </gazebo>-->
  
  <link name="agv_base_link">
   <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="${agv_base_length} ${agv_base_width} ${agv_base_height}" />
      </geometry>
      <material name="White" />
    </visual>
    <inertial>
     <mass value="${agv_base_mass}" />
     <origin xyz="0 0 0" rpy="0 0 0" />
     <cuboid_inertia m="${agv_base_mass}" d="${agv_base_length}" w="${agv_base_width}" h="${agv_base_height}" />
   </inertial>
    <!-- base top -->
    <collision>
      <origin xyz="0 0 ${agv_base_height/4-0.014}" rpy="0 0 0" />
      <geometry>
        <box size="${agv_base_length} ${agv_base_width} ${agv_base_height/2-0.027}" />
      </geometry>
    </collision>
    <!-- base bottom -->
    <collision>
      <origin xyz="0 0 ${-agv_base_height/4-0.0075}" rpy="0 0 0" />
      <geometry>
        <box size="${agv_base_length} ${agv_base_width} ${agv_base_height/2-0.015}" />
      </geometry>
    </collision>
    <!-- four corners -->
    <collision>
      <origin xyz="0.325 0.225 0.0" rpy="0 0 0" />
      <geometry>
        <box size="0.05 0.05 ${agv_base_height}" />
      </geometry>
    </collision>
    <collision>
      <origin xyz="0.325 -0.225 0.0" rpy="0 0 0" />
      <geometry>
        <box size="0.05 0.05 ${agv_base_height}" />
      </geometry>
    </collision>
    <collision>
      <origin xyz="-0.325 0.225 0.0" rpy="0 0 0" />
      <geometry>
        <box size="0.05 0.05 ${agv_base_height}" />
      </geometry>
    </collision>
    <collision>
      <origin xyz="-0.325 -0.225 0.0" rpy="0 0 0" />
      <geometry>
        <box size="0.05 0.05 ${agv_base_height}" />
      </geometry>
    </collision>
  </link>
  <!--<gazebo reference="agv_base_link">
    <material>Gazebo/White</material>
    <gravity>true</gravity>
    <dampingFactor>1.0</dampingFactor>
    <maxVel>1000.0</maxVel>
    <minDepth>0.01</minDepth>
    <mu1>0.0</mu1>
    <mu2>0.0</mu2>
    <fdir1>0 0 0</fdir1>
    <kp>0.0</kp>
    <kd>0.0</kd>
    <selfCollide>false</selfCollide>
    <maxContacts></maxContacts>
    <laserRetro></laserRetro>
  </gazebo>-->

  <!-- Wheels -->
  <!-- <joint name="agv_base_fl_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 ${-M_PI_2/2}" />
    <parent link="agv_base_link"/>
    <child link="agv_base_fl" />
  </joint>
  <link name="agv_base_fl" />
  
  <joint name="agv_base_fr_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 ${M_PI_2/2}" />
    <parent link="agv_base_link"/>
    <child link="agv_base_fr" />
  </joint>
  <link name="agv_base_fr" />
  
  <joint name="agv_base_bl" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 ${M_PI_2/2}" />
    <parent link="agv_base_link"/>
    <child link="agv_base_bl" />
  </joint>
  <link name="agv_base_bl" />
  
  <joint name="agv_base_br_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 ${-M_PI_2/2}" />
    <parent link="agv_base_link"/>
    <child link="agv_base_br" />
  </joint>
  <link name="agv_base_bl" /> -->
  
  <xacro:include filename="$(find launcher)/urdf/wheel/omni_wheel.urdf.xacro" />
  
  <xacro:omni_wheel_250 name="wheel_front_left" parent="agv_base_link">
    <origin xyz="0.2245 0.2245 ${-agv_base_height/2}" rpy="${M_PI_2} 0 ${-M_PI_2/2}" />
    <fdir1>0 0 0</fdir1>
  </xacro:omni_wheel_250>
  <xacro:omni_wheel_250 name="wheel_front_right" parent="agv_base_link">
    <origin xyz="0.2245 -0.2245 ${-agv_base_height/2}" rpy="${-M_PI_2} 0 ${M_PI_2/2}" />
    <fdir1>0 0 0</fdir1>
  </xacro:omni_wheel_250>
  <xacro:omni_wheel_250 name="wheel_back_left" parent="agv_base_link">
    <origin xyz="-0.2245 0.2245 ${-agv_base_height/2}" rpy="${M_PI_2} 0 ${M_PI_2/2}" />
    <fdir1>0 0 0</fdir1>
  </xacro:omni_wheel_250>
  <xacro:omni_wheel_250 name="wheel_back_right" parent="agv_base_link">
    <origin xyz="-0.2245 -0.2245 ${-agv_base_height/2}" rpy="${-M_PI_2} 0 ${-M_PI_2/2}" />
    <fdir1>0 0 0</fdir1>
  </xacro:omni_wheel_250>
  
  <!-- Lidar 
  <xacro:include filename="$(find launcher)/urdf/lidar/lidar.urdf.xacro" />
  
  <xacro:lidar_block name="agvlidar_top" parent="agv_base_link">
    <origin xyz="0.19 0.0 ${agv_base_height/2-0.025}" rpy="0 0 0" />
  </xacro:lidar_block>-->
  <!-- <xacro:lidar_block name="agvlidar_bot" parent="agv_base_link">
    <origin xyz="-0.19 0.0 -0.005" rpy="0 0 0" />
  </xacro:lidar_block> -->
  
  <!-- Camera 
  <xacro:include filename="$(find launcher)/urdf/camera/camera.urdf.xacro" />
  
  <xacro:camera_block name="agvcam_front" parent="agv_base_link">
    <origin xyz="0.35 0.0 0.07" rpy="0 0 0" />
  </xacro:camera_block>
  <xacro:camera_block name="agvcam_back" parent="agv_base_link">
    <origin xyz="-0.35 0.0 0.07" rpy="0 0 ${M_PI}" />
  </xacro:camera_block>
  <xacro:camera_block name="agvcam_left" parent="agv_base_link">
    <origin xyz="0.0 -0.25 0.07" rpy="0 0 ${-M_PI_2}" />
  </xacro:camera_block>
  <xacro:camera_block name="agvcam_right" parent="agv_base_link">
    <origin xyz="0.0 0.25 0.07" rpy="0 0 ${M_PI_2}" />
  </xacro:camera_block>-->

  <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
      <robotNamespace>agv</robotNamespace>
      <controlPeriod>0.001</controlPeriod>
      <robotParam>/robot_description</robotParam>
      <robotSimType>gazebo_ros_control/DefaultRobotHWSim</robotSimType>
    </plugin>
  </gazebo>

</robot>
