<?xml version="1.0"?>
<robot name="lidar" xmlns:xacro="http://ros.org/wiki/xacro">
	<!-- lidar -->
	<xacro:property name="lidar_size" value="0.041" />

	<xacro:macro name="lidar_gazebo" params="name">
		<gazebo reference="${name}">
			<sensor type="ray" name="${name}">
			<pose>${lidar_size/2} 0 0 0 0 0</pose>
			<visualize>false</visualize>
			<update_rate>40</update_rate>
			<ray>
				<scan>
					<horizontal>
						<samples>720</samples>
						<resolution>1</resolution>
						<min_angle>${-M_PI}</min_angle>
						<max_angle>${M_PI}</max_angle>
					</horizontal>
				</scan>
				<range>
					<min>0.15</min>
					<max>12.0</max>
					<resolution>0.001</resolution>
				</range>
			</ray>
			<plugin name="gazebo_ros_base_laser_controller" filename="libgazebo_ros_laser.so">
				<topicName>/scan_${name}</topicName>
				<frameName>${name}</frameName>
			</plugin>
    </sensor>
    
		<!--<material>Gazebo/Blue</material>
		<gravity>true</gravity>
		<dampingFactor>0.0</dampingFactor>
		<maxVel>100.0</maxVel>
		<minDepth>0.01</minDepth>
		<mu1>200.0</mu1>
		<mu2>100.0</mu2>
		<fdir1>1 0 0</fdir1>
		<kp>100000.0</kp>
		<kd>1.0</kd>
		<selfCollide>false</selfCollide>
		<maxContacts></maxContacts>
		<laserRetro></laserRetro>-->
		</gazebo>
	</xacro:macro>
  
	<xacro:macro name="block_lidar" params="name parent xyz:='0 0 0' rpy:='0 0 0'">
		<joint name="${name}_joint" type="fixed">
			<origin xyz="${xyz}" rpy="${rpy}" />
			<parent link="${parent}" />
			<child link="${name}" />
		</joint>

		<link name="${name}">
			<xacro:inertia_cuboid mass="0.1" d="${lidar_size}" w="${lidar_size}" h="${lidar_size}" />
			<xacro:collision_cuboid length="${lidar_size}" width="${lidar_size}" height="${lidar_size}" />
			<xacro:visual_cuboid length="${lidar_size}" width="${lidar_size}" height="${lidar_size}"  material="Blue" />
		</link>
	</xacro:macro>
</robot>
