<?xml version="1.0"?>
<robot name="agv" xmlns:xacro="http://ros.org/wiki/xacro">
  <material name="Black">
    <color rgba="0.0 0.0 0.0 1.0"/>
  </material>

  <material name="White">
    <color rgba="1.0 1.0 1.0 1.0"/>
  </material>
  
  <!-- AGV Base -->
  <xacro:property name="agv_base_height" value="0.27" />
  <xacro:property name="agv_base_width" value="0.5" />
  <xacro:property name="agv_base_length" value="0.7" />
  <xacro:property name="agv_base_mass" value="70.0" />
  
  <!-- Macro for calculating inertia of cube -->
  <xacro:macro name="cuboid_inertia" params="m w d h">
    <inertia  ixx="${m*(w*w+h*h)/12}" ixy = "0" ixz = "0"
              iyy="${m*(d*d+h*h)/12}" iyz = "0"
              izz="${m*(d*d+w*w)/12}" /> 
  </xacro:macro>
  
  
  <link name="base_footprint"/>

  <joint name="base_footprint_agv_base_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0" />
    <parent link="base_footprint"/>
    <child link="agv_base_link" />
    <dynamics damping="0.001" friction="1.0"/>
  </joint>
  <!--<gazebo reference="base_footprint_agv_base_joint">
     <stopCfm>0.0001</stopCfm>
     <stopErp>0.8</stopErp>
     <provideFeedback>true</provideFeedback>
     <implicitSpringDamper>true</implicitSpringDamper>
      <fudgeFactor></fudgeFactor>  
   </gazebo>-->
  
  <link name="agv_base_link">
   <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="${agv_base_length} ${agv_base_width} ${agv_base_height}" />
      </geometry>
      <material name="White" />
    </visual>
    <inertial>
     <mass value="10.0" />
     <origin xyz="0 0 0" rpy="0 0 0" />
     <cuboid_inertia m="10.0" d="1.0" w="1.0" h="1.0" />
   </inertial>
    <!-- base top -->
    <collision>
      <origin xyz="0 0 ${agv_base_height/4-0.014}" rpy="0 0 0" />
      <geometry>
        <box size="${agv_base_length} ${agv_base_width} ${agv_base_height/2-0.027}" />
      </geometry>
    </collision>
    <!-- base bottom -->
    <collision>
      <origin xyz="0 0 ${-agv_base_height/4-0.0075}" rpy="0 0 0" />
      <geometry>
        <box size="${agv_base_length} ${agv_base_width} ${agv_base_height/2-0.015}" />
      </geometry>
    </collision>
    <!-- four corners -->
    <collision>
      <origin xyz="0.325 0.225 0.0" rpy="0 0 0" />
      <geometry>
        <box size="0.05 0.05 ${agv_base_height}" />
      </geometry>
    </collision>
    <collision>
      <origin xyz="0.325 -0.225 0.0" rpy="0 0 0" />
      <geometry>
        <box size="0.05 0.05 ${agv_base_height}" />
      </geometry>
    </collision>
    <collision>
      <origin xyz="-0.325 0.225 0.0" rpy="0 0 0" />
      <geometry>
        <box size="0.05 0.05 ${agv_base_height}" />
      </geometry>
    </collision>
    <collision>
      <origin xyz="-0.325 -0.225 0.0" rpy="0 0 0" />
      <geometry>
        <box size="0.05 0.05 ${agv_base_height}" />
      </geometry>
    </collision>
  </link>
  
  <gazebo reference="agv_base_link">
    <collision>
      <surface>
        <friction>
          <torsional>
            <coefficient>1.0</coefficient>
          </torsional>
          <ode>
            <mu>0</mu>
            <mu2>0</mu2>
            <fdir1>0 0 0</fdir1>
            <slip1>0</slip1>
            <slip2>0</slip2>
          </ode>
        </friction>
      </surface>
    </collision>
  </gazebo>
</robot>
