<?xml version="1.0"?>
<robot name="lidar" xmlns:xacro="http://ros.org/wiki/xacro">
  
  <material name="Blue">
    <color rgba="0.0 0.0 0.8 1.0"/>
  </material>
  
  <!-- lidar -->
  <xacro:property name="lidar_size" value="0.041" />
  
  <xacro:macro name="lidar_block" params="name parent *origin">
   <joint name="${name}_joint" type="fixed">
    <xacro:insert_block name="origin" />
    <parent link="${parent}" />
    <child link="${name}" />
   </joint>

   <link name="${name}">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="${lidar_size} ${lidar_size} ${lidar_size}"/>
      </geometry>
      <material name="Blue" />
    </visual>
    <inertial>
     <mass value="0.1" />
     <origin xyz="0 0 0" rpy="0 0 0" />
     <cuboid_inertia m="0.1" d="${lidar_size}" w="${lidar_size}" h="${lidar_size}" />
   </inertial>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="${lidar_size} ${lidar_size} ${lidar_size}" />
      </geometry>
    </collision>
   </link>
   
   <gazebo reference="${name}">
    <sensor type="ray" name="${name}">
      <pose>${lidar_size/2} 0 0 0 0 0</pose>
      <visualize>false</visualize>
      <update_rate>40</update_rate>
      <ray>
        <scan>
          <horizontal>
            <samples>720</samples>
            <resolution>1</resolution>
            <min_angle>${-M_PI}</min_angle>
            <max_angle>${M_PI}</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.15</min>
          <max>12.0</max>
          <resolution>0.001</resolution>
        </range>
      </ray>
      <plugin name="gazebo_ros_base_laser_controller" filename="libgazebo_ros_laser.so">
        <topicName>/scan_${name}</topicName>
        <frameName>${name}</frameName>
      </plugin>
    </sensor>
    
    <!--<material>Gazebo/Blue</material>
    <gravity>true</gravity>
    <dampingFactor>0.0</dampingFactor>
    <maxVel>100.0</maxVel>
    <minDepth>0.01</minDepth>
    <mu1>200.0</mu1>
    <mu2>100.0</mu2>
    <fdir1>1 0 0</fdir1>
    <kp>100000.0</kp>
    <kd>1.0</kd>
    <selfCollide>false</selfCollide>
    <maxContacts></maxContacts>
    <laserRetro></laserRetro>-->
   </gazebo>

  </xacro:macro>
  
</robot>
